### ISSUE TITLE
Cancelling DisplayDialog: Failed to activate/update license Timeout occured while trying to update license. Please try again later or contact support@unity3d.com

### ISSUE THREAD

**Issue by DreamPWJ** [game-ci/docker#120]
This should not be called in batch mode.    
Jenkins Pipeline 
    sh """
    UNITY_LICENSE=`cat Unity_v2020.x.ulf`
    export  UNITY_LICENSE
     """

**Comment by webbertakken** [comment]
Could you please elaborate on what you think the bug is here?

**Comment by DreamPWJ** [comment]
When I was packing with my personal account, there was a problem of activation authorization，xvfb-run --auto-servernum --server-args=-screen 0 640x480x24 unity-editor -projectPath /my/jenkins/workspace/test-unity-app -quit -batchmode -nographics -force-free -executeMethod UnityBuild.BuildPlatforms -username 406798106@qq.com -password ******

**Comment by webbertakken** [comment]
Thank you for the clarification.

Please note that both [Unity documentation](https://docs.unity3d.com/Manual/CommandLineArguments.html) and [Game CI documentation](https://game.ci/docs/gitlab/activation) indicate that that wouldn't work, due to the command line arguments the Unity editor is expecting.

I'll close this as there is no bug here.
