### ISSUE TITLE
ubuntu-2020.3.25f1-windows-mono-0.15.0 is missing in Docker registry

### ISSUE THREAD

**Issue by flortsch** [game-ci/docker#137]
Hey guys,

happy new year and thank you for bundling Unity for Docker, we are using it inside Gitlab and we are very happy with it :)
However, we noticed that the image for ubuntu-2020.3.25f1-windows-mono-0.15.0 is missing in the Docker registry. According to https://game.ci/docs/docker/versions, indeed there seems to be a problem building this particular image. Any info on what the issue is / one can somehow help / when we can expect a fix for this?

Cheers,
Florian

**Comment by GabLeRoux** [comment]
Indeed, there has been a discussion concerning this on our discord server, here's a link for the discussion:  
https://discord.com/channels/710946343828455455/710946344264794218/922763643681136690

The problem is on Unity's side as it was reproduced with the ui:
![image](https://user-images.githubusercontent.com/1264761/148661467-7ed91d4d-956c-4083-8050-5bfdbad07cd5.png)

I think the outcome of this conversation is to use Unity Hub beta.

> So, the Unity support recommends using Unity Hub beta. By the way, they have added distribution via Debian packages: https://docs.unity3d.com/hub/manual/InstallHub.html

It might be super interesting to try and recreate the hub docker image.

For reference, here's how we're installing hub right now:  
https://github.com/game-ci/docker/blob/c5b7d8e/images/ubuntu/hub/Dockerfile

Would be interesting to see if we can build `ubuntu-2020.3.25f1-windows-mono-0.15.0` using `hub` as a debian package.

**Comment by webbertakken** [comment]
Perhaps we could start releasing all hub versions, i.e. `hub:2.4.5-0.15.0` or `hub:2-0.15.0` and do the same for v3 or v4.

**Comment by webbertakken** [comment]
We have updated our hub image to use 3.0.0 in the latest two [releases](https://github.com/game-ci/docker/releases) (0.16.0 and 0.16.1)

Consequently the image with the version you mentioned was built successfully and you should now be able to use it.

Please see https://game.ci/docs/docker/versions for the latest images and their statuses.

**Comment by flortsch** [comment]
Nice, thank you!
