### ISSUE TITLE
Publish `ltsc2022` tags for Windows

### ISSUE THREAD

**Issue by jlsalmon** [game-ci/docker#189]
**Context**

We are looking to shift our internal CI to GameCI, but our current stack relies on Windows Server 2022 which means we can’t use the pre-built GameCI images for Windows since they are based on `ltsc2019` (and we don’t particularly want to use hyper-v isolation).

**Suggested solution**

Would it be possible to have `ltsc2022` images published as well as `ltsc2019`?

**Considered alternatives**

Considered Hyper-v isolation, but might be prohibitively slow for large projects.

**Comment by webbertakken** [comment]
Right now we're only supporting officially supported operating systems. Since our uploads are sizeable we're not looking to add another version of the same base OS at this time.

However, please feel free to discuss your approach and bumps in the road on our discord and feel to contribute an example docker image to this repository, or instructions for it to our documentation website. That way the community can still help out.

**Comment by jlsalmon** [comment]
@webbertakken thanks for the prompt response! I totally understand your position on this, and I figured this might be the answer I'd get. We will look for alternative solutions in the meantime. 👍
