### ISSUE TITLE
Images missing for Unity 2022.2.0f1 and 2022.1.24f1

### ISSUE THREAD

**Issue by guidoarkesteijn** [game-ci/docker#193]
**Bug description**

Now that Unity has released 2022.2.0f1 official on December 7, 2022. I was hoping to find the new docker images being build and available after a few hours of the release. However I noticed there aren't any Docker image create actions started for it.

Also noticed that for the new 2022.1.24f1 there are no new docker images available.

**How to reproduce**

- Try using the new `unityci/editor:ubuntu-2022.2.0f1-{PLATFORM}-1`
- Notice it erroring out with not being available

**Expected behavior**

After a few hours it should have created the latest Docker Images for the latest releases.

**Additional details**

https://unity.com/releases/editor/archive
https://unity.com/releases/2022-2

**Comment by webbertakken** [comment]
Thanks for letting us know. I'll have a look what's going on soon.

**Comment by guidoarkesteijn** [comment]
Thank you for the quick reply 🎉

**Comment by webbertakken** [comment]
The versions aren't being scraped because the website changed. 
The will be fixed in the issue that is linked above this post.

However, note that there may be additional issues witht 2022.2.x specifically, as Unity has a bug with clang, and another one with with android tools.

**Comment by AndrewKahr** [comment]
As Webber mentioned above there are issues with Android on Linux for IL2CPP on 2022.2.0. I reported the issue which you can find [here](https://issuetracker.unity3d.com/issues/linux-build-fails-with-clang-not-found-errors-when-building-an-il2cpp-android-project-with-armv7-and-arm64-target-architectures) but they've marked it as won't fix since they say it was fixed. My testing still finds it broken and I've tried to get the issue reopened. 

Unfortunately for installing the right android tools via Unity Hub, my issue report seems to have been ignored with no response after months now on both the forums and the bug report backend.
