### ISSUE TITLE
Update Docker Hub images with ubuntu mac-mono fix

### ISSUE THREAD

**Issue by coltbauman-unity** [game-ci/docker#194]
Fixed in #188

Just creating this ticket for tracking so I can get a notification when it's done.

**Comment by davidmfinol** [comment]
#188 has been merged, so closing this issue.

**Comment by cabauman** [comment]
@davidmfinol this issue is related but different from #188. The mac-mono docker images for older Unity versions in docker hub still haven't been updated with this fix. So, I created this ticket for tracking. The [following image](https://hub.docker.com/r/unityci/editor/tags?page=1&name=ubuntu-2021.2.0f1-mac-mono-1&ordering=-name) says updated 10 months ago.

**Comment by davidmfinol** [comment]
So you'd like to keep this issue open until the docker images are updated using the changes from #188 ?

**Comment by cabauman** [comment]
Well, my hope was that creating an issue would serve as a reminder to the maintainers. But if not, I guess it can be closed 😅

**Comment by davidmfinol** [comment]
Closing this issue now that we are publishing v2 of the docker images.
