### ISSUE TITLE
Update ubuntu version from 18.04 to 22.04

### ISSUE THREAD

**Issue by eugeneteoh** [game-ci/docker#215]
**Context**

Ubuntu 18.04 has reached end of life.

**Suggested solution**

Ubuntu images should be upgraded to the latest LTS version, 22.04.

**Considered alternatives**

**Additional details**

Vulkan doesn't work out of the box in ubuntu:18.04 image.

```
$ vulkaninfo
===========
VULKAN INFO
===========

Vulkan Instance Version: 1.1.70

/build/vulkan-UL09PJ/vulkan-1.1.70+dfsg1/demos/vulkaninfo.c:2700: failed with VK_ERROR_INITIALIZATION_FAILED
```

**Comment by webbertakken** [comment]
I agree, it's time.

We're gonna need to sort out which dependencies are needed for 20.04 or 22.04. Ideally the latter, but also depending on what the requirements of Unity Editor are.

**Comment by eugeneteoh** [comment]
Latter is good. Anything I can help with (e.g. which dependencies to look into)? I need it for my CI and I'd rather not have a custom image.

**Comment by webbertakken** [comment]
Sure.

First of all, it's important to understand how to iterate quickly. You can build images locally by following instructions in [DEVELOPMENT.md](https://github.com/game-ci/docker/blob/main/DEVELOPMENT.md)

1. We'll need an upgrade of the [base](https://github.com/game-ci/docker/blob/main/images/ubuntu/base/Dockerfile) image, so that it's based on 22.04.
2. After that, the `hub` and `editor` images can be created. They will have to pass the build process.
3. Finally we'll need to ask a few people to test their use cases based on the changes from the PR. For example it'll need to work with all `targetPlatforms` as well as with `ECS` and `burst` compilation and the default projects with the different render pipelines should run without a hitch as well.

If any good changes were made that are also useful for other platforms:
- We'll need to repeat the same steps for Windows.
- MacOS does not yet have images as per https://github.com/containerd/containerd/discussions/5525

Once done, we'd have to do a major version bump for the images, so that old installations don't automatically start failing.
