### ISSUE TITLE
FFMPEG not found

### ISSUE THREAD

**Issue by danjones1618** [game-ci/docker#95]
**Bug description**
When building a project using WebGL it does not install ffmpeg

**How to reproduce**
Build a project with an Audio File targeting WebGL then search the logs for 'ffmpeg' it will say it's not found

**Expected behavior**
Ffmpeg to be installed

**Additional details**
![image](https://user-images.githubusercontent.com/15719117/111309986-6da77d00-8654-11eb-9fae-c228ed692849.png)
GitHub actions CI:
![image](https://user-images.githubusercontent.com/15719117/111310098-99c2fe00-8654-11eb-9c24-67eb1b5ad229.png)

From a quick look at the `/editor/Dockerfile` I believe the problem is within the [webgl] section
The `grep -v 'webgl'` should be `grep -v WebGL` I think as that is the case required by the unity-builder script.

**Comment by GabLeRoux** [comment]
https://github.com/game-ci/docker/blob/a0c1017d01fa11c9c9adc277f750bac0a578b047/editor/Dockerfile#L162-L170

I'm not sure the `grep -v 'webgl'` is the bug here. the module used here is the one from the image name and not what is provided by unity itself.

Truth is this was solved in https://github.com/game-ci/docker/pull/89
It's just not released yet ;) It will be part of version `0.11`.

https://github.com/game-ci/docker/releases

**Comment by GabLeRoux** [comment]
I'm closing this, but once `0.11` is out, if it still doesn't work, don't hesitate to open a new issue. Also make sure you have a wonderful day 🙌

**Comment by danjones1618** [comment]
Ah thank you for the quick response!

**Comment by danjones1618** [comment]
V0.11 fixed it! Thanks! :smile: :fire:
